version: '3'

services:
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-r 640x480 -f 10 -y
      - CAMERA_DEV=/dev/video0
    ports:
      - "9980:80"
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyACM0
      - /dev/ttyAMA0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    volumes:
      - ./volumes/octoprint:/octoprint

  ispyagentdvr:
    image: doitandbedone/ispyagentdvr
    container_name: ispyagentdvr
    ports:
      - "8090:8090"
      - "3478:3478/udp"
      - "50000-50010:50000-50010/udp"
    volumes:
      - "/appdata/ispyagentdvr/config/:/agent/Media/XML/"
      - "/appdata/ispyagentdvr/media/:/agent/Media/WebServerRoot/Media/"
      - "/appdata/ispyagentdvr/commands:/agent/Commands/"
    #stdin_open: true
    #tty: true